name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Extract zip
        run: unzip ekran_analizor.zip -d .

      - name: Get dependencies
        run: cd screen_analyzer && flutter pub get

      - name: Build APK
        run: cd screen_analyzer && flutter build apk --release

      - uses: actions/upload-artifact@v3
        with:
          name: ekran-analizor-apk
          path: screen_analyzer/build/app/outputs/flutter-apk/app-release.apk
